### ISSUE TITLE
Support optional sticky subheader

### ISSUE THREAD

**Issue by KyleAMathews** [KyleAMathews/react-headroom#5]
This is a cool pattern I saw on [producthunt.com](http://producthunt.com)

## Both headers showing
![screen shot 2015-03-02 at 7 52 20 am](https://cloud.githubusercontent.com/assets/71047/6444266/61829812-c0b1-11e4-97cd-852e0aa5c877.png)

## Only the subheader is now showing
![screen shot 2015-03-02 at 7 52 27 am](https://cloud.githubusercontent.com/assets/71047/6444268/63566880-c0b1-11e4-9271-bc44f89cb8e9.png)

**Comment by SachaG** [comment]
Supporting this would be awesome! Any news on this feature?

**Comment by WickyNilliams** [comment]
You shouldn't need to do anything to support this use-case. IIRC product hunt are using the original headroom, and there is no special support for this. Providing you know the height of the top component of the header, all you need to do is negatively translateY by that amount.

See this fiddle: https://jsfiddle.net/z74ujuoy/

**Comment by KyleAMathews** [comment]
Yeah this has been supported for a while. Just use the `pinStart` prop see http://kyleamathews.github.io/react-headroom/

**Comment by SachaG** [comment]
Thanks, I'll try with the custom CSS example. But I don't really see how `pinStart` would help with this? If I understand correctly it changes when the element gets pinned and unpinned, but it doesn't change how much it gets translated by?

**Comment by KyleAMathews** [comment]
You just want the subheader to be pinned to the top correct? pinStart makes it so the subheader is only pinned once its at the top. Otherwise as soon as you scroll down it'd be snnaped to the top.

**Comment by kici8** [comment]
Please, can you give us an example?

**Comment by hpohlmeyer** [comment]
I think this is not fixed. You can come close to the desired effect, but not fully.

Here is an example:
https://codesandbox.io/s/headroom-double-header-example-i4nc6

If I do not set `pinStart`, the `.headroom-unpinned` class does not get applied before I scrolled past the whole header, including the subheader. After I have done that, it pops back in:

![1](https://user-images.githubusercontent.com/6564077/92086594-ac699a00-edca-11ea-9f54-36ddb4babb87.gif)

To avoid that, `pinStart` can be set to the negative height of the subheader. This is almost the desired outcome, but since `pinStart` is negative now, `.headroom--unfixed` won’t be applied anymore, which means the header stays fixed until we hit the header height an disappears immediately. In the meantime content will be hidden under the header. 

![2](https://user-images.githubusercontent.com/6564077/92086903-1a15c600-edcb-11ea-8e2b-e9027aec9daf.gif)

Currently I do not see a way to work around it, without altering `headroom`. I currently see several ways to resolve this:

1. Update `shouldWork` to handle negative `pinStart` values
2. Let the user provide a custom header height, that overrides the calculated one
3. Add a new property, that can be used to subtract a component from the wrapped content

I can provide a PR if you’d like @KyleAMathews. Maybe you can point me to your prefered solution …
