### ISSUE TITLE
React 15.2.0 and unknown props issue

### ISSUE THREAD

**Issue by kikoanis** [KyleAMathews/react-headroom#86]
So... React 15.2.0 is out and I thought I would play with it and see all the issues that they were talking about for the last month or so.

According to this [https://gist.github.com/jimfb/d99e0678e9da715ccf6454961ef04d1b](https://gist.github.com/jimfb/d99e0678e9da715ccf6454961ef04d1b), they need library maintainers to clean up their code.

Interestingly, the first library I got a warning about is yours (sorry)

I looked at the source code and I think this line is the one responsible for the warning
[https://github.com/KyleAMathews/react-headroom/blob/master/src/index.js#L203](https://github.com/KyleAMathews/react-headroom/blob/master/src/index.js#L203)

Not sure which properties should be excluded but I think the warning is clear enough for which properties to exclude when you render the div

Ideas?

**Comment by kikoanis** [comment]
O.K 

I did  play with it and it seems that if you remove just the aforementioned line
```
 {...this.props}
```
the warning will disappear 

Unless I am mistaken, I do not believe that the passed props on the div element are used for any functionality

Let me know if you are interested in a PR

**Comment by KyleAMathews** [comment]
So it looks like what they want is that instead of passing `this.props` directly we first pull off `style` and any other prop that we're passing explicitly before spreading in `rest`.

So similar to the "good" example, do something like `const { style, ...rest } = props` and then spread in `rest` in the inner div.

Would love a PR for this, thanks!

**Comment by KyleAMathews** [comment]
Merged and made new release, thanks @kikoanis!
